apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app:mern_project
  template:
    metadata:
      labels:
        app:mern_project
    spec:
      containers:
      - name: your-container
        image: akrem106/image
        ports:
        - containerPort: 5000
