version: '3'

services:
  # Service pour le backend (Node.js avec Express)
  backend:
    build:
      context: ./mern-backend
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: "mongodb+srv://akrem:akrem@cluster0.yehlf7w.mongodb.net/?retryWrites=true&w=majority" 

  # Service pour le frontend (React.js)
  frontend:
    build:
      context: ./mern-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
