apiVersion: v1
kind: Service
metadata:
  name: your-service-nodeport
spec:
  type: NodePort
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
