apiVersion: v1
kind: Service
metadata:
  name: your-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app:mern_project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
